### ISSUE TITLE
Automatically detect all the cells

### ISSUE THREAD

**Issue by Dhravya** [nexxeln/sudoku.com-solver#3]
Instead of taking input one by one, which is really slow and frustrating, why not take it automatically?
Possible through one of these methods:
- OpenCV
- [ImageGrab and PyTesseract](https://www.geeksforgeeks.org/python-using-pil-imagegrab-and-pytesseract/)
- Using some javascript (idk how to do with python) you can get the entire grid as-is 

Also, you can make it directly click on the first block to make it more redundant

**Comment by nexxeln** [comment]
maybe ill try using opencv

**Comment by nexxeln** [comment]
this would require tesseract which is gonna limit the number of people using this, as they would have to download an external thing. thats why im not gonna implement this feature.

lemme know if you think of any other method to make the input process quicker and easier.

**Comment by Dhravya** [comment]
if you want to make it work on one website only you can do it easily using selenium

**Comment by nexxeln** [comment]
yeah but i don't want it to be fully automated, i want to run it on a normal browser, not an automatic one.

i still want the user to be involved in some sort of way
