### ISSUE TITLE
Usage of numpy arrays for faster processing

### ISSUE THREAD

**Issue by Dhravya** [nexxeln/sudoku.com-solver#4]
A multi-dimensional NumPy array could make it considerably faster and less resource-intensive
Its pretty easy to do, you can also convert the existing list into a numpy array using something like `n_arr = np.array(grid)`

**Comment by nexxeln** [comment]
can you submit pr lmao

**Comment by Dhravya** [comment]
I could, sure. Thought it could be a nice learning experience for you too haha

**Comment by nexxeln** [comment]
hmm okay
tell me what to do idk much about numpy arrays

**Comment by nexxeln** [comment]
@Dhravya are you free to submit a pr now?

**Comment by Dhravya** [comment]
I will when free

**Comment by Dhravya** [comment]
Done in #6

**Comment by nexxeln** [comment]
thank you!
